### ISSUE TITLE
A small tutorial would be nice!

### ISSUE THREAD

**Issue by nhandt64** [BilliAlpha/discord-transfer#1]
Hi,
I have seen this project (?) and I want to use it on my servers. But I have no experience with Java before. So a short tutorial in the readme would be very helpful.
Thanks!

**Comment by BilliAlpha** [comment]
Hello,
Thanks for your feedback.
I added some basic documentation to the README, could you tell me if that's clear enough for you ?

**Comment by nhandt64** [comment]
Very detailed and LGTM!
Thank you!
