### ISSUE TITLE
Feature Request: Start Date Argument

### ISSUE THREAD

**Issue by IronPegasus** [BilliAlpha/discord-transfer#13]
Fully migrating channels with an extensive message history (100,000+ messages) can take several days to complete. Sometimes, the bot will terminate partway through the migration process with "connection closed" errors. This isn't a big deal since the bot flags migrated messages with a reaction and will pickup where it left off once restarted. However, it seems to start its scan for unflagged messages at the beginning of each channel's history, meaning that sometimes it will scan tens of thousands of messages just to reach where it died. It would be nice if there was an optional `--startdate`/`--date`/etc parameter that would allow specification of where the bot should start scanning for messages.

**Comment by BilliAlpha** [comment]
Glad to know the bot is used for such large servers.
There are several improvements that could be made to reduce the time it takes to migrate so many messages.
This start date argument is a good idea.
I'll look into it if I get some free time.

**Comment by BilliAlpha** [comment]
The last release should be quicker to migrate channels and provides the new `--after` option.

**Comment by IronPegasus** [comment]
I was not expecting such a fast response on this. Thank you so much!
