### ISSUE TITLE
messages no longer copy after toggle on the message content intent to "on"

### ISSUE THREAD

**Issue by AnnaFromPoland** [BilliAlpha/discord-transfer#14]
hello

so previously the messages all copied, but empty (all info BUT the message itself was copied - empty messages, just timestamps and nicknames), to which you advised to set the "message content intent" toggle in bot settings to "on":

![image](https://user-images.githubusercontent.com/16665256/205128637-9032118f-3671-4e08-a0a6-fb0a622a1427.png)

this however makes the messages just to stop being copied at all:

![image](https://user-images.githubusercontent.com/16665256/205128833-00964f18-86f0-474f-9574-7852137c6484.png)

what else could i be doing wrong here?

**Comment by AnnaFromPoland** [comment]
i tried using the previous version of the jar file, that did not help.  
i did not try to toggle off the permission for bot to access the messages, as that seems wrong, but maybe i should do it just to check if it would return to copying the message information, just without the message content.

**Comment by BilliAlpha** [comment]
Could you make sure that the original messages do not have the migrated emote ?
![image](https://user-images.githubusercontent.com/17186697/205459078-3b14e9e2-8ec8-46c0-8782-bef91cf3855f.png)

If they do, you can relaunch the bot with `clean` action instead of `migrate` and it will remove all migrated emotes.

**Comment by AnnaFromPoland** [comment]
i thought about it, but after a couple of seconds i discarded it as a potential issue (esp that i'd prefer to run it by you first as it requires a lot of manual labor to remove every single bot reaction from under every single post).  
now that i know this can be an issue, i'll try this out, and let you know the result!  
(thanks for your patience! i guess this is a good testing occasion for the new settings after that toggle on change? xD)

**Comment by BilliAlpha** [comment]
> esp that i'd prefer to run it by you first as it requires a lot of manual labor to remove every single bot reaction from under every single post

As I said, the bot can remove the reactions by itself, you just have to pass the action `clean` in place of `migrate`.

**Comment by AnnaFromPoland** [comment]
without the reactions the code worked and copied the messages with their contents.  
the clean argument still requires 2 discord servers as 2 more arguments even though it does not copy from & to, that's a skosh unintuitive but took me just like a second to figure out, description says despite the action 2 content sources ought to be given. i just used server1ID twice, as argument 2 and argument 3 as well.
super glad this tool works <3 thanks for making it!
