### ISSUE TITLE
Support Forum transfer?

### ISSUE THREAD

**Issue by icecyclone** [BilliAlpha/discord-transfer#25]
Thank you so much for creating this wonderful thing, which is a near perfect solution to a long-standing problem I had!
Of course, as the title says, it would be great if the transfer of Forum, Threads, etc. could be supported in the future. Thank you again for your creation.

**Comment by BilliAlpha** [comment]
Hello,
Thanks for your message, glad this project could help you.
This feature has already been requested in issue #10 however the Discord4J library still doesn't support Forums and Threads.
They've announced a release should be on the way in the coming months.
