### ISSUE TITLE
Guild ID too long

### ISSUE THREAD

**Issue by ghost** [BilliAlpha/discord-transfer#4]
I tried hardcoding the values, but I'm observing an error that the integer values are too long... am I missing something?

**Comment by BilliAlpha** [comment]
Hello,
Could you give me some more details ?
The project does not use integer as far as I am aware, Discord IDs are saved as longs.

**Comment by ghost** [comment]
These are the guild IDs that I'm passing - guildA=810428750650409041; guildB=815472408555028521, they're throwing NumberFormatException.
I tried hardcoding the values too, but same issue is happening...

**Comment by BilliAlpha** [comment]
Could you show me the command you are trying to run ?

The correct usage would be : `java -jar discord-transfer.jar migrate 810428750650409041 815472408555028521`

PS: I released an update yesterday fixing a bug, please make sure you use the last version.

**Comment by BilliAlpha** [comment]
@kanvstnrn Did you manage to get the bot working or are you still facing the issue ?

**Comment by BilliAlpha** [comment]
I'm closing this, if you still face the issue open a new ticket.
