### ISSUE TITLE
Failing Link in Usernames for Transferred Messages

### ISSUE THREAD

**Issue by ShadeOfTyranny** [BilliAlpha/discord-transfer#9]
When the bot transfers messages from one server to another, the usernames on the messages are clickable links - but when clicking them, I receive a "You don't have access to this link" message.

Do you know why this might be, or what the link is supposed to direct to?

**Comment by BilliAlpha** [comment]
Hi, sorry for the late reply.
The link is supposed to open the DM channel with the author of the message but apparently user IDs have changed ...
I don't think there is a way to fix this right now.

Edit: The link to private channels (DM) have changed, not the IDs, so the link is broken now ...

**Comment by BilliAlpha** [comment]
I have removed the link in the last version since it was broken anyway.
